palette = "light"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "dir"

[character]
success_symbol = "[:](bold ok)"
error_symbol = "[:](bold err)"
vimcmd_symbol = "[❮](vim)"

[git_branch]
format = "[$branch]($style)"
style = "italic branch"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](status) ($ahead_behind$stashed)]($style)"
style = "status2"
conflicted = "!"
untracked = "?"
modified = "~"
staged = "+"
renamed = "»"
deleted = "-"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-white"

[cmd_duration]
format = "[$duration]($style) "
style = "duration"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[palettes.dark]
dir = "#616161"
ok = "#719872"
err = "#BF2172"
vim = "#0099BD"
branch = "#719872"
status = "#9A7599"
status2 = "#0099BD"
duration = "#719872"

[palettes.light]
dir = "#616161"
ok = "#719872"
err = "#BF2172"
vim = "#0099BD"
branch = "#719872"
status = "#9A7599"
status2 = "#0099BD"
duration = "#719872"
