return {
  {
    name = 'theme',
    repo = 'vague2k/vague.nvim',
    concern = 'appearance',
    capabilities = { 'appearance' },
    deps = {
      'junegunn/seoul256.vim',
    },
  },
  {
    name = 'nvim-treesitter',
    repo = 'nvim-treesitter/nvim-treesitter',
    version = 'main',
    concern = 'editing',
    capabilities = { 'editing' },
  },
  {
    name = 'treesitter-context',
    repo = 'nvim-treesitter/nvim-treesitter-context',
    concern = 'editing',
    capabilities = { 'editing' },
  },
  {
    name = 'vimwiki',
    repo = 'vimwiki/vimwiki',
    version = 'dev',
    concern = 'notes',
    capabilities = { 'notes' },
  },
  {
    name = 'blink',
    repo = 'saghen/blink.cmp',
    concern = 'completion',
    capabilities = { 'completion' },
    build = 'cargo build --release',
  },
  {
    name = 'mini.pairs',
    repo = 'nvim-mini/mini.pairs',
    concern = 'editing',
    capabilities = { 'editing' },
  },
  {
    name = 'mini.icons',
    repo = 'nvim-mini/mini.icons',
    concern = 'platform',
    capabilities = { 'platform', 'appearance' },
  },
  {
    name = 'mini.starter',
    repo = 'nvim-mini/mini.starter',
    concern = 'platform',
    capabilities = { 'platform', 'navigation' },
  },
  {
    name = 'mini.snippets',
    repo = 'nvim-mini/mini.snippets',
    concern = 'completion',
    capabilities = { 'completion' },
  },
  {
    name = 'oil',
    repo = 'stevearc/oil.nvim',
    concern = 'navigation',
    capabilities = { 'navigation' },
  },
  {
    name = 'better-escape',
    repo = 'max397574/better-escape.nvim',
    concern = 'editing',
    capabilities = { 'editing' },
  },
  {
    name = 'todo-comments',
    repo = 'folke/todo-comments.nvim',
    concern = 'editing',
    capabilities = { 'editing' },
  },
  {
    name = 'gitsigns',
    repo = 'lewis6991/gitsigns.nvim',
    concern = 'git',
    capabilities = { 'git' },
  },
  {
    name = 'markdown-preview',
    repo = 'iamcco/markdown-preview.nvim',
    concern = 'notes',
    capabilities = { 'notes' },
    build = 'cd app && npm install',
  },
  {
    name = 'img-clip',
    repo = 'hakonharnes/img-clip.nvim',
    concern = 'notes',
    capabilities = { 'notes' },
  },
  {
    name = 'render-markdown',
    repo = 'MeanderingProgrammer/render-markdown.nvim',
    concern = 'notes',
    capabilities = { 'notes', 'appearance' },
  },
  {
    name = 'noice',
    repo = 'folke/noice.nvim',
    concern = 'appearance',
    capabilities = { 'appearance', 'ui' },
    deps = {
      'MunifTanjim/nui.nvim',
      { name = 'notify', repo = 'rcarriga/nvim-notify' },
    },
  },
  {
    name = 'notify',
    repo = 'rcarriga/nvim-notify',
    concern = 'appearance',
    capabilities = { 'appearance', 'ui' },
  },
  {
    name = 'conform',
    repo = 'stevearc/conform.nvim',
    concern = 'formatting',
    capabilities = { 'formatting' },
  },
  {
    name = 'minuet-ai',
    repo = 'milanglacier/minuet-ai.nvim',
    concern = 'completion',
    capabilities = { 'completion' },
    deps = { 'nvim-lua/plenary.nvim' },
  },
  {
    name = 'dap-view',
    repo = 'igorlfs/nvim-dap-view',
    concern = 'debug',
    capabilities = { 'debug' },
  },
  {
    name = 'snacks',
    repo = 'folke/snacks.nvim',
    concern = 'platform',
    capabilities = { 'search', 'git', 'terminal', 'ui', 'navigation' },
  },
  {
    name = 'winsep',
    repo = 'nvim-zh/colorful-winsep.nvim',
    concern = 'appearance',
    capabilities = { 'appearance' },
  },
  {
    name = 'rainbow-delimiters',
    repo = 'HiPhish/rainbow-delimiters.nvim',
    concern = 'editing',
    capabilities = { 'editing' },
    provider_host = 'https://gitlab.com/',
    config = 'indent-blankline',
  },
  {
    name = 'indent-blankline',
    repo = 'lukas-reineke/indent-blankline.nvim',
    concern = 'editing',
    capabilities = { 'editing' },
  },
  {
    name = 'flash',
    repo = 'folke/flash.nvim',
    concern = 'navigation',
    capabilities = { 'navigation' },
  },
  {
    name = 'overseer',
    repo = 'stevearc/overseer.nvim',
    concern = 'tasks',
    capabilities = { 'tasks' },
  },
  {
    name = 'lualine',
    repo = 'nvim-lualine/lualine.nvim',
    concern = 'appearance',
    capabilities = { 'appearance' },
  },
  {
    name = 'dap',
    repo = 'mfussenegger/nvim-dap',
    concern = 'debug',
    capabilities = { 'debug' },
    deps = { 'mason-org/mason.nvim' },
  },
  -- { name = 'smear-cursor', repo = 'sphamba/smear-cursor.nvim' },
  { name = 'toggleterm', repo = 'akinsho/toggleterm.nvim', concern = 'platform' },
  {
    name = 'mole',
    repo = 'zion-off/mole.nvim',
    concern = 'notes',
    deps = {
      'MunifTanjim/nui.nvim',
    },
  },
}
