format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#CDCDCD"

[character]
success_symbol = "[:](bold #F3BE7C)"
error_symbol = "[:](bold #D8647E)"
vimcmd_symbol = "[❮](#7FA563)"

[git_branch]
format = "[$branch]($style)"
style = "italic #F3BE7C"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](#BB9DBD) ($ahead_behind$stashed)]($style)"
style = "#6E94B2"
conflicted = "!"
untracked = "?"
modified = "~"
staged = "+"
renamed = "»"
deleted = "-"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-white"

[cmd_duration]
format = "[$duration]($style) "
style = "#7FA563"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
