local pack = require 'pack'
pack.install {
  plugins = {
    -- themes
    -- { name = 'vague', repo = 'vague2k/vague.nvim' },
    -- { name = 'teide', repo = 'serhez/teide.nvim' },
    { name = 'petrolnoir', repo = 'connormxfadden/petrolnoir.nvim' },
    -- themes

    { name = 'melange', repo = 'savq/melange-nvim' },
    { name = 'nvim-treesitter', repo = 'nvim-treesitter/nvim-treesitter', version = 'main' },
    { name = 'treesitter-context', repo = 'nvim-treesitter/nvim-treesitter-context' },
    { name = 'vimwiki', repo = 'vimwiki/vimwiki', version = 'dev' },
    {
      name = 'blink',
      repo = 'saghen/blink.cmp',
      build = 'cargo build --release',
    },
    { name = 'friendly-snippets', repo = 'rafamadriz/friendly-snippets' },
    { name = 'mini.pairs', repo = 'nvim-mini/mini.pairs' },
    { name = 'mini.icons', repo = 'nvim-mini/mini.icons' },
    { name = 'mini.starter', repo = 'nvim-mini/mini.starter' },
    { name = 'mini.snippets', repo = 'nvim-mini/mini.snippets' },
    { name = 'oil', repo = 'stevearc/oil.nvim' },
    { name = 'better-escape', repo = 'max397574/better-escape.nvim' },
    { name = 'todo-comments', repo = 'folke/todo-comments.nvim' },
    { name = 'gitsigns', repo = 'lewis6991/gitsigns.nvim' },
    { name = 'img-clip', repo = 'hakonharnes/img-clip.nvim' },
    {
      name = 'markdown-preview',
      repo = 'iamcco/markdown-preview.nvim',
      build = 'cd app && npm install',
    },
    { name = 'lazygit', repo = 'kdheepak/lazygit.nvim' },
    { name = 'fidget', repo = 'j-hui/fidget.nvim' },
    { name = 'conform', repo = 'stevearc/conform.nvim' },
    { name = 'smear-cursor', repo = 'sphamba/smear-cursor.nvim' },
    { name = 'fzf-lua', repo = 'ibhagwan/fzf-lua' },
    { name = 'claude-code', repo = 'greggh/claude-code.nvim', deps = { 'nvim-lua/plenary.nvim' } },
    { name = 'opencode', repo = 'NickvanDyke/opencode.nvim' },
    { name = 'snacks', repo = 'folke/snacks.nvim' },
    { name = 'lualine', repo = 'nvim-lualine/lualine.nvim' },
    { name = 'winsep', repo = 'nvim-zh/colorful-winsep.nvim' },
    { name = 'rainbow-delimiters', repo = 'HiPhish/rainbow-delimiters.nvim', provider_host = 'https://gitlab.com/' },
    { name = 'indent-blankline', repo = 'lukas-reineke/indent-blankline.nvim' },
    { name = 'flash', repo = 'folke/flash.nvim' },
    {
      name = 'dap',
      repo = 'mfussenegger/nvim-dap',
      deps = { 'mason-org/mason.nvim' },
    },
    { name = 'dap-view', repo = 'igorlfs/nvim-dap-view' },
    {
      name = 'codecompanion',
      repo = 'olimorris/codecompanion.nvim',
      deps = { 'nvim-lua/plenary.nvim' },
    },
  },
  setup_dir = vim.fn.stdpath 'config' .. '/lua/plugins/',
}
