live_config_reload = true

[env]
TERM = "alacritty"

[shell]
# run with tmux
args = ["new-session", "-A", "-D", "-s", "main"]
program = "/usr/local/bin/tmux"

# style
[window]
blur = true
dynamic_padding = true
opacity = 0.75
decorations = "Buttonless"
option_as_alt = "Both"
padding = { x = 4, y = 0 }

[colors]
# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x002b36"
blue = "0x839496"
cyan = "0x93a1a1"
green = "0x586e75"
magenta = "0x6c71c4"
red = "0xcb4b16"
white = "0xfdf6e3"
yellow = "0x657b83"

[colors.normal]
black = "0x002b36"
blue = "0x268bd2"
cyan = "0x2aa198"
green = "0x859900"
magenta = "0xd33682"
red = "0xdc322f"
white = "0xeee8d5"
yellow = "0xb58900"

[colors.primary]
background = "0x001217"
foreground = "0x708183"

# font
[font]
size = 14.0

[font.bold]
family = "MesloLGMDZ Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGMDZ Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGMDZ Nerd Font Mono"


# keymaps

# command mode
# (Control + q + :) to (Command + :)
[[keyboard.bindings]]
chars = "\u0011:"
key = "Semicolon"
mods = "Command"

# command mode
# (Control + q + :) to (Command + Shift + :)
[[keyboard.bindings]]
chars = "\u0011:"
key = "Semicolon"
mods = "Command|Shift"

# split horizontally
# (Control + q + ") to (Command + Shift + d)
[[keyboard.bindings]]
chars = "\u0011\""
key = "D"
mods = "Command|Shift"

# split vertically
# (Control + q + %) to (Command + d)
[[keyboard.bindings]]
chars = "\u0011%"
key = "D"
mods = "Command"

# new tab
# (Control + q + c) to (Command + t)
[[keyboard.bindings]]
chars = "\u0011c"
key = "T"
mods = "Command"

# close pane
# (Control + q + X) to (Command + w)
[[keyboard.bindings]]
chars = "\u0011X"
key = "W"
mods = "Command"

# next pane
# (Control + q + o) to (Command + o)
[[keyboard.bindings]]
chars = "\u0011o"
key = "O"
mods = "Command"

# switch pane
# (Control + q, Control + o) to (Command + Shift + o)
[[keyboard.bindings]]
chars = "\u0011\u000F"
key = "O"
mods = "Command|Shift"

# next tab
# (Control + q + p) to (Command + Shift + t)
[[keyboard.bindings]]
chars = "\u0011p"
key = "P"
mods = "Control"

# resize pane
# (Control + q + H) to (Command + Left)
[[keyboard.bindings]]
chars = "\u0011H"
key = "Left"
mods = "Command"

# (Control + q + J) to (Command + Down)
[[keyboard.bindings]]
chars = "\u0011J"
key = "Down"
mods = "Command"

# (Control + q + K) to (Command + Up)
[[keyboard.bindings]]
chars = "\u0011K"
key = "Up"
mods = "Command"

# (Control + q + L) to (Command + Right)
[[keyboard.bindings]]
chars = "\u0011L"
key = "Right"
mods = "Command"

# move to next word
# (ESC + F) to (Alt + Right)
[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

# move to previous word
# (ESC + B) to (Alt + Left)
[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

# move to start of line
# (ESC + O + H) to (Command + Left)
[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

# move to end of line 
# (ESC + O + F) to (Command + Right)
[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

# delete all inputs
[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

# delete previous word
# (ESC + Delete) to (Alt + BackSpace)
[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"
